# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Klotz's blog
email: agc.klotz@gmail.com
description: >
  Andrew Klotz is a software engineer

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://klotzandrew.com" # the base hostname & protocol for your site
twitter_username: klotzandrew
github_username:  KlotzAndrew

permalink: /blog/:title

name: 'Andrew Klotz'
author: 'Andrew Klotz'

# Build settings
markdown: kramdown
